// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/toy_jni.proto

// Protobuf Java Version: 3.25.1
package com.github.kgrech.toyjni.proto;

public interface RequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:toy_jni.Request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>uint64 response_delay = 2;</code>
   * @return The responseDelay.
   */
  long getResponseDelay();
}
