// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/toy_jni.proto

// Protobuf Java Version: 3.25.1
package com.github.kgrech.toyjni.proto;

public interface ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:toy_jni.Response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .toy_jni.Response.Success success = 1;</code>
   * @return Whether the success field is set.
   */
  boolean hasSuccess();
  /**
   * <code>optional .toy_jni.Response.Success success = 1;</code>
   * @return The success.
   */
  com.github.kgrech.toyjni.proto.Response.Success getSuccess();
  /**
   * <code>optional .toy_jni.Response.Success success = 1;</code>
   */
  com.github.kgrech.toyjni.proto.Response.SuccessOrBuilder getSuccessOrBuilder();

  /**
   * <code>optional .toy_jni.Response.Error error = 2;</code>
   * @return Whether the error field is set.
   */
  boolean hasError();
  /**
   * <code>optional .toy_jni.Response.Error error = 2;</code>
   * @return The error.
   */
  com.github.kgrech.toyjni.proto.Response.Error getError();
  /**
   * <code>optional .toy_jni.Response.Error error = 2;</code>
   */
  com.github.kgrech.toyjni.proto.Response.ErrorOrBuilder getErrorOrBuilder();
}
