// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/toy_jni.proto

// Protobuf Java Version: 3.25.1
package com.github.kgrech.toyjni.proto;

public final class ToyJni {
  private ToyJni() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_toy_jni_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_toy_jni_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_toy_jni_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_toy_jni_Response_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_toy_jni_Response_Success_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_toy_jni_Response_Success_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_toy_jni_Response_Error_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_toy_jni_Response_Error_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026protobuf/toy_jni.proto\022\007toy_jni\"2\n\007Req" +
      "uest\022\017\n\007message\030\001 \001(\t\022\026\n\016response_delay\030" +
      "\002 \001(\004\"\272\001\n\010Response\022/\n\007success\030\001 \001(\0132\031.to" +
      "y_jni.Response.SuccessH\000\210\001\001\022+\n\005error\030\002 \001" +
      "(\0132\027.toy_jni.Response.ErrorH\001\210\001\001\032\032\n\007Succ" +
      "ess\022\017\n\007message\030\001 \001(\t\032\036\n\005Error\022\025\n\rerror_m" +
      "essage\030\001 \001(\tB\n\n\010_successB\010\n\006_errorB\"\n\036co" +
      "m.github.kgrech.toyjni.protoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_toy_jni_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_toy_jni_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_toy_jni_Request_descriptor,
        new java.lang.String[] { "Message", "ResponseDelay", });
    internal_static_toy_jni_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_toy_jni_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_toy_jni_Response_descriptor,
        new java.lang.String[] { "Success", "Error", });
    internal_static_toy_jni_Response_Success_descriptor =
      internal_static_toy_jni_Response_descriptor.getNestedTypes().get(0);
    internal_static_toy_jni_Response_Success_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_toy_jni_Response_Success_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_toy_jni_Response_Error_descriptor =
      internal_static_toy_jni_Response_descriptor.getNestedTypes().get(1);
    internal_static_toy_jni_Response_Error_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_toy_jni_Response_Error_descriptor,
        new java.lang.String[] { "ErrorMessage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
