[package]
name = "toy-jni"
version = "1.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0"
jni = "0.21"
prost = "0.12"
tokio = { version = "1.29", features = ["full"] }

[build-dependencies]
prost-build = "0.12"